[package]
name = "rift_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false, features = ["bevy_sprite", "bevy_text", "bevy_ui", "bevy_core_pipeline", "bevy_render", "bevy_asset", "png"] }
rand = "0.8.5"
