name: CI

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main

# Define environment variables
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Rust toolchain
      - name: Install Rust 0.8.5
        uses: dtol

